-- start_matchsubs
--
-- m/^ERROR:  Error on receive from seg0.*: server closed the connection unexpectedly/
-- s/^ERROR:  Error on receive from seg0.*: server closed the connection unexpectedly/ERROR: server closed the connection unexpectedly/
--
-- end_matchsubs

-- start_ignore
create extension if not exists matrixts;
-- end_ignore

CREATE TABLE sheap_foo(c1 text, c2 text) using sortheap;
CREATE INDEX sheap_idx on sheap_foo using sortheap_btree(c1, c2);

-- Test crash recovery
-- init_tape: error/crash before xlog 
1: select gp_inject_fault('inittape_before_xlog', 'error', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('inittape_before_xlog', 'reset', 2);
1: analyze sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;
-- panic
1: select gp_inject_fault('inittape_before_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('inittape_before_xlog', 'reset', 2);
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;
-- inittape: error/crash after xlog
1: select gp_inject_fault('inittape_after_xlog', 'error', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('inittape_after_xlog', 'reset', 2);
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;
-- panic
1: select gp_inject_fault('inittape_after_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('inittape_after_xlog', 'reset', 2);
1: select * from sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;

-- dump_tuples: crash/error
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: select gp_inject_fault('dump_tuples_before_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('dump_tuples_before_xlog', 'reset', 2);
1: select * from sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: select gp_inject_fault('dump_tuples_after_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('dump_tuples_after_xlog', 'reset', 2);
1: select * from sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;
-- new tapesets: crash
1: select gp_inject_fault('new_tapesets_before_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('new_tapesets_before_xlog', 'reset', 2);
1: select * from sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;
1: select gp_inject_fault('new_tapesets_after_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('new_tapesets_after_xlog', 'reset', 2);
1: select * from sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;

-- new header: crash
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: select gp_inject_fault('new_tapeheader_before_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: insert into sheap_foo select i, 'session1' from generate_series(11, 15) i;
1: select gp_inject_fault('new_tapeheader_before_xlog', 'reset', 2);
1: select * from sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '5';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '5';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: select gp_inject_fault('new_tapeheader_after_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: insert into sheap_foo select i, 'session1' from generate_series(11, 15) i;
1: select gp_inject_fault('new_tapeheader_after_xlog', 'reset', 2);
1: select * from sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '5';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '5';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;

-- new header: crash
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: select gp_inject_fault('tape_insert_flush', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: insert into sheap_foo select i, 'session1' from generate_series(11, 15) i;
1: select gp_inject_fault('tape_insert_flush', 'reset', 2);
1: select * from sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;

-- merge crash
1: select gp_inject_fault('merge_done', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: insert into sheap_foo select i, 'session1' from generate_series(11, 15) i;
-- except fail and wait at most 30 seconds 
1: select pg_sleep(10) from sheap_foo limit 3; 
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c2 = 'session1';
-- force a vacuum
1: vacuum sheap_foo;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;

-- vacuum crash
1: select gp_inject_fault('vacuum_done', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: insert into sheap_foo select i, 'session1' from generate_series(11, 15) i;
-- except fail and wait at most 30 seconds 
1: select pg_sleep(10) from sheap_foo limit 3; 
1: select * from sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
-- re-trigger a merge and vacuum
1: select gp_inject_fault('vacuum_done', 'reset', 2);
1: select gp_inject_fault('vacuum_done', 'suspend', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(16, 20) i;
1: insert into sheap_foo select i, 'session1' from generate_series(21, 25) i;
1: select * from sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c1 = '22';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c1 = '22';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: select gp_wait_until_triggered_fault('vacuum_done', 1, 2);
1: select gp_inject_fault('vacuum_done', 'resume', 2);
1: select gp_inject_fault('vacuum_done', 'reset', 2);
1: select * from sheap_foo;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c1 = '22';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '1';
1: select * from sheap_foo where c1 = '22';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;

-- freespace: allocate crash
1: select gp_inject_fault('freepage_alloc_before_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('freepage_alloc_before_xlog', 'reset', 2);
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;
1: select gp_inject_fault('freepage_alloc_after_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('freepage_alloc_after_xlog', 'reset', 2);
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;

-- freespace: newleaf crash
1: select gp_inject_fault('newleaf_before_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('newleaf_before_xlog', 'reset', 2);
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;
1: select gp_inject_fault('newleaf_after_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('newleaf_after_xlog', 'reset', 2);
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;

-- freespace: newroot crash
1: select gp_inject_fault('newroot_before_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('newroot_before_xlog', 'reset', 2);
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;
1: select gp_inject_fault('newroot_after_xlog', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
1: select gp_inject_fault('newroot_after_xlog', 'reset', 2);
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;

-- freespace: recycle crash
1: select gp_inject_fault('freepage_recycle', 'panic', 2);
1: insert into sheap_foo select i, 'session1' from generate_series(1, 5) i;
1: insert into sheap_foo select i, 'session1' from generate_series(6, 10) i;
-- except fail and wait at most 30 seconds 
1: select pg_sleep(10) from sheap_foo limit 3; 
1: insert into sheap_foo select i, 'session1' from generate_series(11, 15) i;
1: set enable_indexscan to off;
1: set enable_bitmapscan to off;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c1 = '11';
1: select * from sheap_foo where c2 = 'session1';
1: set enable_seqscan to off;
1: set enable_indexscan to on;
1: select * from sheap_foo where c1 = '8';
1: select * from sheap_foo where c1 = '9';
1: select * from sheap_foo where c1 = '11';
1: select * from sheap_foo where c2 = 'session1';
1: reset enable_indexscan;
1: reset enable_bitmapscan;
1: reset enable_seqscan;
1: TRUNCATE sheap_foo;
