{
 "title": "MatrixDB Dashboard",
 "tags": [
  "MatrixDB",
  "Dashboard"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Select Cluster to View",
    "query": "SELECT n.nspname FROM pg_namespace n\nINNER JOIN pg_class c\nON c.relnamespace = n.oid\nAND c.relname = 'matrix_manager_config'"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT hostname FROM gp_segment_configuration GROUP BY hostname ORDER BY min(content)"
   },
   { "name": "severity_level_var", "label": "Log Level", "query": "PANIC,FATAL,ERROR,WARNING" }
  ]
 },
 "panels": [
  {
   "title": "MatrixDB Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Version[1] FROM (SELECT regexp_matches(VERSION(), '(MatrixDB[^)]*)') AS Version) A;\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  state AS \"time\",\n  state\nFROM ${cluster}.segstate\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(sess_id)-1 AS \"Connection(s)\" FROM pg_catalog.pg_stat_activity"
    }
   ]
  },
  {
   "title": "Uptime (master)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT EXTRACT(EPOCH FROM now() - pg_postmaster_start_time())::bigint AS \"MatrixDB\""
    },
    {
     "rawSql": "SELECT\n  uptime AS \"time\",\n  uptime AS \"OS Uptime\"\nFROM ${cluster}.os_uptime\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "WITH org(t, o, u, s, w, a) AS (\n    SELECT\n      $__timeGroupAlias(ts,$__interval),\n      avg((metrics->>'usage_guest')::real + (metrics->>'usage_guest_nice')::real + (metrics->>'usage_steal')::real),\n      avg((metrics->>'usage_user')::real + (metrics->>'usage_nice')::real),\n      avg((metrics->>'usage_system')::real + (metrics->>'usage_irq')::real + (metrics->>'usage_softirq')::real),\n      avg((metrics->>'usage_iowait')::real),\n      avg(100 - (metrics->>'usage_idle')::real)\n    FROM ${cluster}.system\n    WHERE\n      $__timeFilter(ts) AND\n      category = 'cpu' AND\n      device = 'cpu-total' AND\n      host IN ($host)\n    GROUP BY 1\n)\nSELECT t AS \"time\"\n  , o AS \"Other\"\n  , s AS \"System\"\n  , u AS \"User\"\n  , w AS \"IOWait\"\n  , a As \"Total\"\nFROM org\nWHERE t <> (SELECT max(t) FROM org)\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  id,\n  state\nFROM ${cluster}.segdetails\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "WITH org(t, u, b, c) AS (\n    SELECT\n      $__timeGroupAlias(ts,$__interval),\n      avg(((metrics->>'total')::bigint - (metrics->>'free')::bigint - COALESCE((metrics->>'buffered')::bigint, 0) - COALESCE((metrics->>'cached')::bigint, 0) - COALESCE((metrics->>'sreclaimable')::bigint, 0)) / (metrics->>'total')::real * 100) AS \"Used\",\n      avg(COALESCE((metrics->>'buffered')::bigint, 0) / (metrics->>'total')::real * 100) AS \"Buff\",\n      avg((COALESCE((metrics->>'cached')::bigint, 0) + COALESCE((metrics->>'sreclaimable')::bigint, 0)) / (metrics->>'total')::real * 100) AS \"Cache\"\n    FROM ${cluster}.system\n    WHERE\n      $__timeFilter(ts) AND\n      category = 'mem' AND\n      host IN ($host)\n    GROUP BY 1\n)\nSELECT t AS \"time\"\n  , u AS \"Used\"\n  , b AS \"Buff\"\n  , c AS \"Cache\"\nFROM org\nWHERE t <> (SELECT max(t) FROM org)\nORDER BY 1\n;"
    }
   ]
  },
  {
   "title": "Free Disk Space (Master Instances)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  100 * free_bytes / total_bytes AS \"free_pct\"\nFROM ${cluster}.master_disk_usage\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  free_bytes AS \"free_bytes\"\nFROM ${cluster}.master_disk_usage\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Space in Use (Master Instances)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  100 * (total_bytes - free_bytes) / total_bytes AS \"used_pct\"\nFROM ${cluster}.master_disk_usage\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  total_bytes - free_bytes AS \"used_bytes\"\nFROM ${cluster}.master_disk_usage\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Free Disk Space (Segment Instances)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  100 * free_bytes / total_bytes AS \"free_pct\"\nFROM ${cluster}.seg_disk_usage\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  free_bytes\nFROM ${cluster}.seg_disk_usage\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Disk Space in Use (Segment Instances)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  100 * (total_bytes - free_bytes) / total_bytes AS \"used_pct\"\nFROM ${cluster}.seg_disk_usage\nORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  total_bytes - free_bytes AS \"used_bytes\"\nFROM ${cluster}.seg_disk_usage\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "WITH org(t, h, m) AS (\n  SELECT $__timeGroupAlias(ts,$__interval)\n    , host\n    , metrics\n  FROM ${cluster}.system s\n  WHERE $__timeFilter(ts)\n    AND category = 'system'\n    AND host IN ($host)\n),\nper_host_per_t(t, l1, l5, l15) AS (\n    SELECT t\n      , avg((m->>'load1')::float)\n      , avg((m->>'load5')::float)\n      , avg((m->>'load15')::float)\n    FROM org\n    WHERE t <> (SELECT max(t) FROM org)\n    GROUP BY t, h\n)\nSELECT t AS \"time\", avg(l1) AS \"Load1\", avg(l5) AS \"Load5\", avg(l15) AS \"Load15\"\nFROM per_host_per_t\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "DiskIO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "WITH org(t, h, d, m) AS (\n    SELECT\n      $__timeGroupAlias(ts, $__interval),\n      host,\n      device, -- diskio has device name\n      metrics\n    FROM ${cluster}.system\n    WHERE $__timeFilter(ts)\n      AND category = 'diskio'\n      AND host IN ($host)\n),\nper_tag_per_t(t, h, d, rb, wb) AS (\n    SELECT\n      t, h, d,\n      min(m->>'read_bytes')::bigint,\n      min(m->>'write_bytes')::bigint\n    FROM org\n    GROUP BY t, h, d\n),\ndelta(t, dt, drb, dwb, mint) AS (\n    SELECT t,\n      t - lag(t, 1) OVER (PARTITION BY h, d ORDER BY t) AS dt,\n      GREATEST(rb - lag(rb, 1) OVER (PARTITION BY h, d ORDER BY t), 0) AS drb,\n      GREATEST(wb - lag(wb, 1) OVER (PARTITION BY h, d ORDER BY t), 0) AS dwb,\n      first_value(t) OVER (PARTITION BY h, d ORDER BY t) AS mint\n    FROM per_tag_per_t\n),\nfilter(t, dt, drb, dwb) AS (\n    SELECT t, dt, drb, dwb\n    FROM delta\n    WHERE dt > 0\n      AND t <> mint\n)\nSELECT t AS \"time\"\n  , sum(drb/dt)::bigint AS \"Read\"\n  , sum(dwb/dt)::bigint AS \"Write\"\nFROM filter\nWHERE t <> (SELECT max(t) FROM filter)\nGROUP BY t\nORDER BY t"
    }
   ]
  },
  {
   "title": "Database Log",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  logtime::timestamp with time zone AS \"time\",\n  replace(logsegment, 'seg', '') AS logsegment,\n  logseverity,\n  logmessage,\n  loguser,\n  logdatabase,\n  loghost\nFROM matrixmgr_internal.local_logs\nWHERE\n  logseverity IN ($severity_level_var)\nORDER BY 1 DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "WITH org(t, h, d, m) AS (\n    SELECT\n      $__timeGroupAlias(ts, $__interval),\n      host,\n      device, -- diskio has device name\n      metrics\n    FROM ${cluster}.system\n    WHERE $__timeFilter(ts)\n      AND category = 'net'\n      AND device <> 'all'\n      AND host IN ($host)\n),\nper_tag_per_t(t, h, d, rb, wb) AS (\n    SELECT\n      t, h, d,\n      min(m->>'bytes_recv')::bigint,\n      min(m->>'bytes_sent')::bigint\n    FROM org\n    GROUP BY t, h, d\n),\ndelta(t, dt, drb, dwb, mint) AS (\n    SELECT t,\n      t - lag(t, 1) OVER (PARTITION BY h, d ORDER BY t) AS dt,\n      GREATEST(rb - lag(rb, 1) OVER (PARTITION BY h, d ORDER BY t), 0) AS drb,\n      GREATEST(wb - lag(wb, 1) OVER (PARTITION BY h, d ORDER BY t), 0) AS dwb,\n      first_value(t) OVER (PARTITION BY h, d ORDER BY t) AS mint\n    FROM per_tag_per_t\n),\nfilter(t, dt, drb, dwb) AS (\n    SELECT t, dt, drb, dwb\n    FROM delta\n    WHERE dt > 0\n      AND t <> mint\n)\nSELECT t AS \"time\"\n  , sum(drb/dt)::bigint AS \"Recv\"\n  , sum(dwb/dt)::bigint AS \"Send\"\nFROM filter\nWHERE t <> (SELECT max(t) FROM filter)\nGROUP BY t\nORDER BY t\n;"
    }
   ]
  },
  {
   "title": "Process",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "WITH org(t, h, m) AS (\n    SELECT\n      $__timeGroupAlias(ts, $__interval),\n      host,\n      metrics\n    FROM ${cluster}.system\n    WHERE $__timeFilter(ts)\n      AND category = 'processes'\n      AND host IN ($host)\n),\nper_tag_per_t(t, total, blocked, paging, running, sleeping, idle) AS (\n    SELECT\n      t,\n      avg((m->>'total')::bigint),\n      avg((m->>'blocked')::bigint),\n      avg((m->>'paging')::bigint),\n      avg((m->>'running')::bigint),\n      avg((m->>'sleeping')::bigint),\n      avg((m->>'idle')::bigint)\n    FROM org\n    GROUP BY t, h\n)\nSELECT\n  t AS \"time\",\n  sum(total - blocked - paging - running - sleeping - idle) AS \"Other\",\n  sum(blocked + paging) AS \"Blocked\",\n  sum(sleeping + idle) AS \"Sleep\",\n  sum(running) AS \"Running\"\nFROM per_tag_per_t\nWHERE t <> (SELECT max(t) FROM per_tag_per_t)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}